# 所有的关于数据库方面的配置放到这里
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

#    数据库相关信息已修改，供测试使用（许兴军）
    url: jdbc:mysql://81.71.89.149:3306/leetcode?useSSL=false&userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: leetcode
    password: leetcode
    type: com.zaxxer.hikari.HikariDataSource # 使用数据源默认光 Hikari
  # redis
#  redis相关信息已修改，供测试使用（许兴军）
  redis:
    host: 81.71.89.149
    port: 63799
  config:
    activate:
      on-profile: db
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size:  10MB
#mp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台sql的日志.
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0 #初始值为0
  # 实体扫描，多个package用逗号或者分号分隔【list和java.lang.list 冲突】
  mapper-locations: classpath:/mapper/sys/*.xml   #add by zzc
#  type-aliases-package: com.leetcode.web.entity

