bean:
 # 这里不能用双引号，并且不知道为什么，没关系，一样的。能用就行。
 baseFilePath: 'D:/Enviroment/java/diligent-bee/diligent-bee/ftcloud/ftcloud/ftcloud/file'
 privateKey: '永远选择去中正确的事，不是没做会不会后悔，是做了不后悔就可以了'
 # redis验证码过期时间 单位秒 s
 redisSiveTime: 300
 #年轻 token 的时间为 5 小时
 yangToken: 10000
 #老年 token 的时间为 3 天(老年就需要更新新 token)
 oldToken: 30000

spring:
  config:
    activate:
      on-profile: bean
aliyun:
  sms:
    accessKeyId:LTAI4G787zGFcsXWWEFaHCGN
    accessKeySecret:6q4nGASjy55d2cfrdGJhTQwSkyOdG5
    template_code:
    sign_name: